// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_METADATA_TFLITE_GPU_GL_DATA_H_
#define FLATBUFFERS_GENERATED_METADATA_TFLITE_GPU_GL_DATA_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"
#include "workgroups_generated.h"

namespace tflite {
namespace gpu {
namespace gl {
namespace data {

struct FlowMetadata;
struct FlowMetadataBuilder;

struct FlowMetadata FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef FlowMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WORKGROUPS = 4
  };
  const tflite::gpu::gl::data::CustomWorkgroups *workgroups() const {
    return GetPointer<const tflite::gpu::gl::data::CustomWorkgroups *>(VT_WORKGROUPS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_WORKGROUPS) &&
           verifier.VerifyTable(workgroups()) &&
           verifier.EndTable();
  }
};

struct FlowMetadataBuilder {
  typedef FlowMetadata Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_workgroups(flatbuffers::Offset<tflite::gpu::gl::data::CustomWorkgroups> workgroups) {
    fbb_.AddOffset(FlowMetadata::VT_WORKGROUPS, workgroups);
  }
  explicit FlowMetadataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FlowMetadataBuilder &operator=(const FlowMetadataBuilder &);
  flatbuffers::Offset<FlowMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FlowMetadata>(end);
    return o;
  }
};

inline flatbuffers::Offset<FlowMetadata> CreateFlowMetadata(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<tflite::gpu::gl::data::CustomWorkgroups> workgroups = 0) {
  FlowMetadataBuilder builder_(_fbb);
  builder_.add_workgroups(workgroups);
  return builder_.Finish();
}

inline const tflite::gpu::gl::data::FlowMetadata *GetFlowMetadata(const void *buf) {
  return flatbuffers::GetRoot<tflite::gpu::gl::data::FlowMetadata>(buf);
}

inline const tflite::gpu::gl::data::FlowMetadata *GetSizePrefixedFlowMetadata(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<tflite::gpu::gl::data::FlowMetadata>(buf);
}

inline const char *FlowMetadataIdentifier() {
  return "AFFL";
}

inline bool FlowMetadataBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, FlowMetadataIdentifier());
}

inline bool VerifyFlowMetadataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<tflite::gpu::gl::data::FlowMetadata>(FlowMetadataIdentifier());
}

inline bool VerifySizePrefixedFlowMetadataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<tflite::gpu::gl::data::FlowMetadata>(FlowMetadataIdentifier());
}

inline void FinishFlowMetadataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<tflite::gpu::gl::data::FlowMetadata> root) {
  fbb.Finish(root, FlowMetadataIdentifier());
}

inline void FinishSizePrefixedFlowMetadataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<tflite::gpu::gl::data::FlowMetadata> root) {
  fbb.FinishSizePrefixed(root, FlowMetadataIdentifier());
}

}  // namespace data
}  // namespace gl
}  // namespace gpu
}  // namespace tflite

#endif  // FLATBUFFERS_GENERATED_METADATA_TFLITE_GPU_GL_DATA_H_
